model:
  name: improved_yolov8s
  backbone: C2f-Faster-EMA
  neck: FPN-PAN
  head: Detect-Dyhead
  input_size:
  - 640
  - 640
  activation: ReLU
  reg_max: 16
  lr0: 0.004
  weight_decay: 5e-4
data:
  paths:
  - ./database/China_MotorBike
  - ./database/United_States
training:
  batch_size: 8
  epochs: 200
  optimizer: SGD
  momentum: 0.937
  weight_decay: 5e-4
  scheduler: cosine
  warmup_epochs: 5
  fl_gamma: 2.0
loss:
  bbox_loss: CIoU
  cls_loss: FocalLoss
  reg_max: 16
  fl_gamma: 2.0
  class_weights:
  - 0.3185475499993563
  - 0.46781877278413464
  - 0.8114432697074188
  - 1.5711847065435502
  - 1.8310057009655396
data_augmentation:
  resize:
  - 640
  - 640
  mosaic: 0.7
  mixup: 0.2
  copy_paste: 0.1
  cutout: 0.3
  degrees: 10.0
  translate: 0.1
  scale: 0.5
  shear: 0.2
  perspective: 0.0
  flip_ud: 0.1
  flip_lr: 0.5
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  blur: 0.01
  gray: 0.01
  contrast: 0.3
  brightness: 0.2
post_processing:
  confidence_threshold: 0.001
  nms_threshold: 0.5
classes:
  names:
  - Longitudinal Cracks
  - Transverse Cracks
  - Alligator Cracks
  - Potholes
  - Repair
